### ISSUE TITLE
sxr_adapter project cause crash

### ISSUE THREAD

**Issue by kismeter** [sxrsdk/sxrsdk#111]
I try sxr-arcore demo, finally find out that the app crash on sxr_adapter. when try to find out why it's crash, I didn't see sxr_adapter project in sxrsdk. is sxr_adapter closed source? can you help fix this? or release the code if it's open. 

```
 #00 pc 00010ae6  /data/app/com.samsungxr.arcore.simplesample.ar-WDbWmRWLnXAMBJyQ7JeGcA==/lib/arm/libsxr-fr.so
```

**Comment by liaxim** [comment]
There are multiple variants of the app. Please use the monoscopicDebug or oculusDebug variants.

**Comment by kismeter** [comment]
> There are multiple variants of the app. Please use the monoscopicDebug or oculusDebug variants.

how to use monoscopic variants? I set 
```
useLocalDependencies=true
sxr_runtime_as_apk=true
only_monoscopic=true
```
it's generate daydream variants

**Comment by kismeter** [comment]
ok, so sxr_adapter is closed source, right?

**Comment by thomasflynn** [comment]
yes.  it is only meant for the experimental headset we had at our developer conference.  The supported platforms are Oculus, DayDream, and Monoscopic.  in AndroidStudio, there is a menu option for build variant (or is it called build flavor?).  That's what you want to look for.  If you're building the demos from the command line, it'll look something like:  ./gradlew sxr-arcore:installMonoscopicDebug

**Comment by kismeter** [comment]
@thomasflynn Does Samsung have any plan to let us try out arDebug variants?
