### ISSUE TITLE
build new libassimp.so for sxrsdk

### ISSUE THREAD

**Issue by kismeter** [sxrsdk/sxrsdk#113]
I'm trying to rebuild libassimp.so for sxrsdk, when replace the prebuilt libassimp.so, I met link errors. can you share the original build flags for libassimp.so?

**Comment by NolaDonato** [comment]
We made changes to the assimp source to fix import of GLTF files. I will make sure our repo is up to date and will provide you with a link to our version of assimp shortly.

**Comment by NolaDonato** [comment]
I have merged in all of our changes to assimp. You can find the version we use in branch "gvrfassimp" of this repository.

https://github.com/NolaDonato/assimp/tree/gvrfassimp
 The build scripts we use are in there as well so you can see what options we use.

**Comment by liaxim** [comment]
@kismeter Are you good now? Can we close the issue?
