### ISSUE TITLE
SXRTextViewNode setTextColor sometime ignored, regardless of backend used

### ISSUE THREAD

**Issue by joturako** [sxrsdk/sxrsdk#36]
__What I'm trying to do:__
- Create 10 numbers in space and give them blue color.

__What I expected:__
- Have 10 numbers in space and each of them is painted blue.

__What I got:__
- __Sometime__ one of the number is not rendered in blue, but white, that mean the `setTextColor` is ignored.

__The code in question__
The loop
````
for (int i = 1; i < 10; i++) {
            float originZ = -i * 4.0f;
            SXRTextViewNode nodeI = createTextNode(String.format("%d", i), originZ);
            nodeI.getRenderData().setRenderingOrder(100 - i);
            numberList.add(nodeI);
            mainScene.addNode(nodeI);
        }
````
And
````
private SXRTextViewNode createTextNode(String text, float originZ) {
        SXRTextViewNode textObj = new SXRTextViewNode(sxrContext, 1.0f, 1.0f, text);
        textObj.setTypeface(sxrContext, "Open_Sans/OpenSans-Regular.ttf", PLAIN);
        textObj.setRefreshFrequency(SXRTextViewNode.IntervalFrequency.HIGH);

        textObj.getTransform().setPosition(0f, 4f, originZ);
        textObj.setTextSize(16);
        textObj.setTextColor(Color.BLUE);
        textObj.setBackGround(null);

        SXRTextViewNode textBackObj = new SXRTextViewNode(sxrContext, 1.0f, 1.0f, text);
        textBackObj.getTransform().setRotationByAxis(180f, 0, 1, 0);
        textBackObj.getTransform().setPosition(0, 0, 0);
        textBackObj.setTextSize(16);
        textBackObj.setTextColor(Color.RED);
        textBackObj.setBackGround(null);
        textObj.addChildObject(textBackObj);
        return textObj;
    }
````

Note:
- I tested in monoscopic and oculus and the problem appears in both of the backend. I haven't had a throughout look and a clear understanding of the engine. Do you have any idea what's causing this bug so I can fix them and make a PR?

**Comment by sushantojal** [comment]
@joturako, having trouble reproducing your issue. I'm consistently getting the correct output:
![out](https://user-images.githubusercontent.com/11925179/48381593-7c9b5080-e691-11e8-9e23-e43520720971.png)
Which device are you using for development?

**Comment by liaxim** [comment]
@joturako Can you please share with us a complete sample? I tried on 4 different phones and on Oculus Go, tried a lot more text nodes, tried adding them from different threads.. could not reproduce a single time.

**Comment by liaxim** [comment]
@joturako Does not making the setRefreshFrequency call make any difference?

**Comment by liaxim** [comment]
Ok, with IntervalFrequency.LOW it did reproduce for me. It is likely a long standing bug.

**Comment by mwitchwilliams** [comment]
Took a look with X3D and my text color is not changing either. Pretty certain we set text color using diffuseColor.  When trying to change the text color using the following code in X3D's AnimationInteractivityManager.java:
`scriptObjectToDefinedItem.getSXRMaterial().setVec4("diffuse_color", sfColor.getRed(), sfColor.getGreen(), sfColor.getBlue(), 1.0f);`

I included two demo's plus the required font's in the zip below:
- 'text_ChangeDiffuseColor.x3d' should change the diffuseColor of the text "_VERY LONG NEW TEXT_" when rolling over the Cylinder or Cone, but it does NOT work.
- 'textChange_MultObj.x3d' changes the diffuseColor of the Cone when rolling over either the Cylinder or Cone, and it works. 

![screenshot_20181113-104921_sxr-x3d-demo](https://user-images.githubusercontent.com/18128830/48436629-026fd800-e734-11e8-85da-8fdf982e673f.jpg)

[demo.zip](https://github.com/sxrsdk/sxrsdk/files/2577642/demo.zip)

**Comment by liaxim** [comment]
@joturako Let me know how https://github.com/sxrsdk/sxrsdk/pull/48 works for you.

**Comment by liaxim** [comment]
@joturako Not quite sure what you mean. Did the fix for the textviewnode work or did it not? Thanks.

**Comment by joturako** [comment]
@liaxim sorry my bad, i haven't check the #48, what I meant is I downloaded the demo and run everything new again and it is as you said.
Tomorrow I will try checkout #48.

**Comment by joturako** [comment]
@liaxim I inserted a log into the ```SXRTextViewNode``` ```refresh``` function and seem the ```setTextColor``` function doesn't trigger it at all, while the text change do trigger a refresh call.

**Comment by liaxim** [comment]
@joturako You should've tested your app and code. The x3d scripts thing is unrelated issue (the textviewnode color is set via setTextColor, not "diffuseColor" for example). That is not what you posted as an issue. Let me know how your app works please.

**Comment by joturako** [comment]
@liaxim hah, sorry I didn't even think of that, currently developing something else that doesn't touch the text problem so I forgot, will report back tomorrow. Bear with me one more day please :(

**Comment by joturako** [comment]
@liaxim It seems the problem is gone now, but I need to keep an eye on this for a little longer. Thanks for the fix :dancing_men:

**Comment by liaxim** [comment]
@joturako Can we close the issue?

**Comment by joturako** [comment]
@liaxim  ah yes, I meant if I have the problem re-appearing I will just re-open this.

**Comment by liaxim** [comment]
@mwitchwilliams Your problem is in x3d itself. The "diffuseColor" needs to be translated to the corresponding SXRTextViewNode.setTextColor (like by the ShapePostParsing method). On roll over though the diffuserColor of the material is being set directly by SetResultsFromScript.
